## To install any not yet on user's system

# install.packages('rjags')
# install.packages('MASS')
# install.packages('ggplot2')
# install.packages('metaSEM')
# install.packages('metafor')
# install.packages('parallel')
# install.packages('dplyr')
# install.packages('mvtnorm')
# install.packages('kableExtra')
# install.packages('lavaan')
# install.packages('tidyr')


library(rjags)
library(MASS)
library(ggplot2)
library(metaSEM)
library(metafor)
library(parallel)
library(dplyr)
library(mvtnorm)
library(kableExtra)
library(lavaan)
library(tidyr)